# Generated by Django 3.2 on 2021-04-30 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('start_bid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(blank=True)),
                ('status', models.BooleanField(default=True)),
                ('image', models.URLField(blank=True)),
                ('category', models.CharField(blank=True, max_length=64, unique=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
